receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
  # otlp:
  # otlp/dapr:
  #     # The receiver will listen on endpoint: "0.0.0.0:9090".
  #     endpoint: 0.0.0.0:9090
  # zipkin:
  #   endpoint: 0.0.0.0:9411

exporters:
  azuremonitor:
    # endpoint is the uri used to communicate with Azure Monitor
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    # instrumentation_key is the unique identifer for your Application Insights resource
    instrumentation_key: 24dd1990-a772-4311-8f04-474058a753b1
    # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
    maxbatchinterval: 10s
  logging:
    # loglevel: debug

  # zipkin:
  #   url: "http://zipkin:9411/api/v2/spans"
  #   format: proto

  # jaeger_thrift:
  #   url: "http://jaeger:14268/api/traces"

processors:
  batch:
  queued_retry:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  # extensions: [health_check]
  pipelines:
    traces:
      # receivers: [opencensus, otlp/dapr, zipkin]
      receivers: [opencensus]
      # exporters: [azuremonitor, zipkin, jaeger_thrift, logging]
      exporters: [azuremonitor, logging]
      processors: [batch, queued_retry]
