# receivers:
#     opencensus:
#       endpoint: 0.0.0.0:55678
#     zipkin:
#       endpoint: :9411
#     jaeger:
#       protocols:
#         thrift_http:
#           endpoint: "0.0.0.0:14268"
  
#   exporters:
#     # opencensus:
#     #   endpoint: "otel-collector:55680"
#     #   insecure: true
#     azuremonitor:
#       # endpoint is the uri used to communicate with Azure Monitor
#       endpoint: "https://dc.services.visualstudio.com/v2/track"
#       # instrumentation_key is the unique identifer for your Application Insights resource
#       instrumentation_key: 24dd1990-a772-4311-8f04-474058a753b1
#       # maxbatchsize is the maximum number of items that can be queued before calling to the configured endpoint
#       maxbatchsize: 1
#       # maxbatchinterval is the maximum time to wait before calling the configured endpoint.
#       maxbatchinterval: 10s
#     # logging:
#     #   loglevel: debug
  
#   processors:
#     batch:
#     queued_retry:
  
#   extensions:
#     pprof:
#       endpoint: :1777
#     zpages:
#       endpoint: :55679
#     health_check:
  
#   service:
#     extensions: [health_check, pprof, zpages]
#     pipelines:
#       traces:
#         receivers: [opencensus, zipkin, jaeger]
#         exporters: [azuremonitor]
#         processors: [batch, queued_retry]
#       metrics:
#         receivers: [opencensus]
#         exporters: [logging]