apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: otel-collector
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: otel-collector
    spec:
      containers:
      - args:
        - --config=/etc/otel-collector-config.yml
        image: ayushisingh/otelcontribcol:06172020v2
        imagePullPolicy: ""
        name: otel-collector
        ports:
        - containerPort: 1777
        - containerPort: 8888
        - containerPort: 14268
        - containerPort: 55678
        - containerPort: 13133
        resources: {}
        volumeMounts:
        - mountPath: /etc/otel-collector-config.yml
          name: otel-collector-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: otel-collector-claim0
        persistentVolumeClaim:
          claimName: otel-collector-claim0
status: {}
